#!/usr/bin/python3

import argparse
import os
import subprocess
import sys


def add_arguments(parser):
    parser.add_argument("--output", help="Output directory", required=True)
    parser.add_argument("--config", help="Config file", required=False)
    parser.add_argument("--type", help="Image type", required=True)
    parser.add_argument("--rootfs", help="Root filesystem", required=False)
    parser.add_argument("--dry-run", help="Dry run", action="store_true")
    parser.add_argument("image", help="Image ref")


def main():
    if os.geteuid() != 0:
        print(
            "bibcli is not run as root, this might be an issue without podman being configured to use a (rootful) machine by default",
            file=sys.stderr,
        )
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command")
    build_parser = subparsers.add_parser("build", help="Build an image")
    add_arguments(build_parser)

    manifest_parser = subparsers.add_parser("manifest", help="Genereate a manifest")
    add_arguments(manifest_parser)

    args = parser.parse_args()

    # Always pass an absolute path to podman, otherwise it might create a volume, instead of bind-mount
    output = os.path.abspath(args.output)
    config = os.path.abspath(args.config) if args.config else None

    if not os.path.exists(output):
        os.makedirs(output)

    extra_run_flags = []
    if config:
        extra_run_flags += ["-v", f"{config}:/config.toml"]

    extra_bib_flags = []
    if args.rootfs:
        extra_bib_flags += ["--rootfs", args.rootfs]

    bib_cmd = "build"
    if args.command == "manifest":
        bib_cmd = "manifest"

    cmd = (
        [
            "podman",
            "run",
            "--rm",
            "--privileged",
            "--security-opt",
            "label=disable",
            "-it",
            "-v",
            "/var/lib/containers/storage:/var/lib/containers/storage",
            "-v",
            f"{output}:/output",
            "--pull=newer",
        ]
        + extra_run_flags
        + ["quay.io/centos-bootc/bootc-image-builder"]
        + [bib_cmd]
        + ["--local", "--type", args.type]
        + extra_bib_flags
        + [
            args.image,
        ]
    )

    if args.dry_run:
        print(" ".join(cmd))
        return 0

    subprocess.run(
        cmd,
        check=True,
    )


if __name__ == "__main__":
    sys.exit(main())
